// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using eBordo.Api.Database;

namespace eBordo.Api.Migrations
{
    [DbContext(typeof(eBordoContext))]
    [Migration("20210913200204_add-table-drzava")]
    partial class addtabledrzava
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.9")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("eBordo.Api.Database.Drzava", b =>
                {
                    b.Property<int>("drzavaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("nazivDrzave")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("zastavaUrl")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("drzavaId");

                    b.ToTable("drzave");
                });
#pragma warning restore 612, 618
        }
    }
}
